export const ARCGIS_MAP_PARAMS = {
  bboxSR: '',
  layers: '',
  layerDefs: '',
  imageSR: '',
  historicMoment: '',
  format: 'png',
  transparent: true,
  dpi: '',
  time: '',
  layerTimeOptions: '',
  dynamicLayers: '',
  gdbVersion: '',
  mapScale: '',
  rotation: '',
  datumTransformations: '',
  layerParameterValues: '',
  mapRangeValues: '',
  layerRangeValues: '',
  f: 'image',
};
